local L = LibStub("AceLocale-3.0"):NewLocale("DraiksBrokerDB", "frFR", true)

L["Draiks Broker ILevel"] = true
L["Display"] = "Affichage"
L["Specify what to display"] = "Spécifiez Quoi Montrer"
L["Main Settings"] = "Arrangements principaux"
L["Show Level"] = "Montrez de Niveau"
L["Show Character Levels"] = "Montrez Les Niveaux de Caractère"
L["Factions and Realms"] = "Factions et Royaumes"
L["All Factions"] = "Toutes Les Factions"
L["All factions will be displayed"] = "Toutes les factions seront montrées"
L["All Realms"] = "Toutes Les Royaumes"
L["All realms will be displayed"] = "Tous les Royaumes seront montrés"
L["Sort Order"] = "Ordre de Sorte"
L["Sort Type"] = "Type de Sorte"
L["Select the sort type"] = "Choisissez le type de sorte"
L["By Name"] = "Par Nom"
L["By Level"] = "Par Level"
L["By Item Level"] = "Par Item Level"
L["By Money"] = "Par Money"
L["Sort in reverse order"] = "Sorte à l'envers l'ordre"
L["Use the curent sort type in reverse order"] = "Employez la sorte curent saisissent l'ordre d'inversion"
L["Ignore Characters"] = "Ignorez les Caractères"
L["Hide characters from display"] = "Caractères de peau d'affichage"
L["Realm"] = "Royaumes"
L["Character Name"] = "Nom de Caractère"
L["UI"] = true
L["Set UI options"] = "Placez la balance d'UI"
L["Scale"] = "Balance"
L["Scale the tooltip (70% to 150%)"] = "Mesurez le tooltip (70% 150%)"
L["Opacity"] = "Opacité"
L["% opacity of the tooltip background"] = "Opacité du fond de tooltip"
L["Show Bars"] = "Montrez Les Barres"
L["Display Table Rows as colored bars with white text"] = "Montrez les rangées de Tableau en tant que discriminations raciales avec le texte blanc"
L["dil"] = true
L["draiksbrokerilevel"] = true
L["draiksilvl"] = true
L["draiksilevel"] = true
L["Character iLevel Breakdown"] = "Panne d'iLevel de caractère"
L["Calculate Own Average iLevel"] = "Calculez pour posséder l'iLevel moyen"
L["Calculate your own average iLevel based on what you have equiped instead of using the Blizzard Reported Average iLevel"] = "Calculez votre propre iLevel moyen basé sur ce que vous avez équipé au lieu d'employer la tempête de neige rapportée l'iLevel moyen"
L["Show Party"] = "Montrez la partie"
L["Show the ilvl of party and raid members from your server."] = "Montrez l'ilvl de la partie et pillez les membres de votre serveur"
L["Save Party"] = true
L["Save the ilvl of party and raid members from your server."] = true
L["Current Group"] = true
L["Group and Raid Options"] = true