local L = LibStub("AceLocale-3.0"):NewLocale("DraiksBrokerDB", "deDE", true)

L["% opacity of the tooltip background"] = "% Opazität des tooltip Hintergrundes" -- Needs review
L["All Factions"] = "Alle Fraktionen" -- Needs review
L["All Realms"] = "Alle Realms" -- Needs review
L["All factions will be displayed"] = "Alle Fraktionen werden angezeigt" -- Needs review
L["All realms will be displayed"] = "Alle Realms werden angezeigt" -- Needs review
-- L["By Item Level"] = "By Item Level"
L["By Level"] = "Nach Farbe" -- Needs review
L["By Money"] = "Nach Geld" -- Needs review
L["By Name"] = "Nach Namen" -- Needs review
L["Calculate Own Average iLevel"] = "Berechnen Sie, durchschnittliches iLevel zu besitzen" -- Needs review
L["Calculate your own average iLevel based on what you have equiped instead of using the Blizzard Reported Average iLevel"] = "Berechnen Sie Ihr eigenes durchschnittliches iLevel, das basiert auf, was Sie ausgerüstet haben, anstatt, den Blizzard zu benutzen, der durchschnittliches iLevel berichtet wird" -- Needs review
L["Character Name"] = "Buchstaben-Name" -- Needs review
L["Character iLevel Breakdown"] = "Buchstabe iLevel Zusammenbruch" -- Needs review
-- L["Current Group"] = "Current Group"
L["Display"] = "Anzeige" -- Needs review
L["Display Table Rows as colored bars with white text"] = "Zeigen Sie Tabellen-Reihen als farbige Stäbe mit weißem Text an" -- Needs review
-- L["Draiks Broker ILevel"] = "Draiks Broker ILevel"
L["Factions and Realms"] = "Fraktionen und Realms" -- Needs review
-- L["Group and Raid Options"] = "Group and Raid Options"
L["Hide characters from display"] = "Versteckt Charaktere" -- Needs review
L["Ignore Characters"] = "Ignoriere Charaktere" -- Needs review
L["Main Settings"] = "Haupteinstellungen" -- Needs review
L["Opacity"] = "Transparenz" -- Needs review
-- L["Realm"] = "Realm"
-- L["Save Party"] = "Save Party"
-- L["Save the ilvl of party and raid members from your server."] = "Save the ilvl of party and raid members from your server."
L["Scale"] = "Skala" -- Needs review
L["Scale the tooltip (70% to 150%)"] = "Stufen Sie das tooltip ein (70% bis 150%)" -- Needs review
L["Select the sort type"] = "Wählen Sie die Art-Art vor" -- Needs review
L["Set UI options"] = "Stellen Sie UI Wahlen ein" -- Needs review
L["Show Bars"] = "Zeigen Sie Stäbe" -- Needs review
L["Show Character Levels"] = "Zeigen Sie Buchstaben-Niveaus" -- Needs review
L["Show Level"] = "Stellen Sie gleich dar" -- Needs review
L["Show Party"] = "Zeigen Sie Partei" -- Needs review
L["Show the ilvl of party and raid members from your server."] = "Zeigen Sie das ilvl der Partei- und Überfallmitglieder von Ihrem Bediener" -- Needs review
L["Sort Order"] = "Art-Auftrag" -- Needs review
L["Sort Type"] = "Sortiertyp" -- Needs review
L["Sort in reverse order"] = "Sortiere in umgekehrter Reihenfolge" -- Needs review
-- L["Specify what to display"] = "Specify what to display"
-- L["UI"] = "UI"
L["Use the curent sort type in reverse order"] = "Sortiert nach ausgewähltem Sortiertyp in umgekehrter Reihenfolge" -- Needs review
-- L["dil"] = "dil"
-- L["draiksbrokerilevel"] = "draiksbrokerilevel"
-- L["draiksilevel"] = "draiksilevel"
-- L["draiksilvl"] = "draiksilvl"
