local L = LibStub("AceLocale-3.0"):NewLocale("DraiksBrokerDB", "enUS", true)

L["Draiks Broker ILevel"] = true
L["Display"] = true
L["Specify what to display"] = true
L["Main Settings"] = true
L["Show Level"] = true
L["Show Character Levels"] = true
L["Factions and Realms"] = true
L["All Factions"] = true
L["All factions will be displayed"] = true
L["All Realms"] = true
L["All realms will be displayed"] = true
L["Sort Order"] = true
L["Sort Type"] = true
L["Select the sort type"] = true
L["By Name"] = true
L["By Level"] = true
L["By Item Level"] = true
L["By Money"] = true
L["Sort in reverse order"] = true
L["Use the curent sort type in reverse order"] = true
L["Ignore Characters"] = true
L["Hide characters from display"] = true
L["Realm"] = true
L["Character Name"] = true
L["UI"] = true
L["Set UI options"] = true
L["Scale"] = true
L["Scale the tooltip (70% to 150%)"] = true
L["Opacity"] = true
L["% opacity of the tooltip background"] = true
L["Show Bars"] = true
L["Display Table Rows as colored bars with white text"] = true
L["dil"] = true
L["draiksbrokerilevel"] = true
L["draiksilvl"] = true
L["draiksilevel"] = true
L["Character iLevel Breakdown"] = true
L["Calculate Own Average iLevel"] = true
L["Calculate your own average iLevel based on what you have equiped instead of using the Blizzard Reported Average iLevel"] = true
L["Show Party"] = true
L["Show the ilvl of party and raid members from your server."] = true
L["Save Party"] = true
L["Save the ilvl of party and raid members from your server."] = true
L["Current Group"] = true
L["Group and Raid Options"] = true
