local L = LibStub("AceLocale-3.0"):NewLocale("DraiksBrokerDB", "frFR", true)

L["% opacity of the tooltip background"] = "Opacité du fond de tooltip" -- Needs review
L["All Factions"] = "Toutes Les Factions" -- Needs review
L["All Realms"] = "Toutes Les Royaumes" -- Needs review
L["All factions will be displayed"] = "Toutes les factions seront montrées" -- Needs review
L["All realms will be displayed"] = "Tous les Royaumes seront montrés" -- Needs review
L["By Item Level"] = "Par Item Level" -- Needs review
L["By Level"] = "Par Level" -- Needs review
L["By Money"] = "Par Money" -- Needs review
L["By Name"] = "Par Nom" -- Needs review
L["Calculate Own Average iLevel"] = "Calculez pour posséder l'iLevel moyen" -- Needs review
L["Calculate your own average iLevel based on what you have equiped instead of using the Blizzard Reported Average iLevel"] = "Calculez votre propre iLevel moyen basé sur ce que vous avez équipé au lieu d'employer la tempête de neige rapportée l'iLevel moyen" -- Needs review
L["Character Name"] = "Nom de Caractère" -- Needs review
L["Character iLevel Breakdown"] = "Panne d'iLevel de caractère" -- Needs review
-- L["Current Group"] = "Current Group"
L["Display"] = "Affichage" -- Needs review
L["Display Table Rows as colored bars with white text"] = "Montrez les rangées de Tableau en tant que discriminations raciales avec le texte blanc"
-- L["Draiks Broker ILevel"] = "Draiks Broker ILevel"
L["Factions and Realms"] = "Factions et Royaumes" -- Needs review
-- L["Group and Raid Options"] = "Group and Raid Options"
L["Hide characters from display"] = "Caractères de peau d'affichage" -- Needs review
L["Ignore Characters"] = "Ignorez les Caractères" -- Needs review
L["Main Settings"] = "Arrangements Principaux" -- Needs review
L["Opacity"] = "Opacité" -- Needs review
L["Realm"] = "Royaumes" -- Needs review
-- L["Save Party"] = "Save Party"
-- L["Save the ilvl of party and raid members from your server."] = "Save the ilvl of party and raid members from your server."
L["Scale"] = "Balance" -- Needs review
L["Scale the tooltip (70% to 150%)"] = "Mesurez le tooltip (70% 150%)" -- Needs review
L["Select the sort type"] = "Choisissez le type de sorte" -- Needs review
L["Set UI options"] = "Placez la balance d'UI" -- Needs review
L["Show Bars"] = "Montrez Les Barres" -- Needs review
L["Show Character Levels"] = "Montrez Les Niveaux de Caractère" -- Needs review
L["Show Level"] = "Montrez de Niveau" -- Needs review
L["Show Party"] = "Montrez la partie" -- Needs review
L["Show the ilvl of party and raid members from your server."] = "Montrez l'ilvl de la partie et pillez les membres de votre serveur" -- Needs review
L["Sort Order"] = "Ordre de Sorte" -- Needs review
L["Sort Type"] = "Type de Sorte" -- Needs review
L["Sort in reverse order"] = "Sorte à l'envers l'ordre" -- Needs review
L["Specify what to display"] = "Spécifiez Quoi Montrer" -- Needs review
-- L["UI"] = "UI"
L["Use the curent sort type in reverse order"] = "Employez la sorte curent saisissent l'ordre d'inversion" -- Needs review
-- L["dil"] = "dil"
-- L["draiksbrokerilevel"] = "draiksbrokerilevel"
-- L["draiksilevel"] = "draiksilevel"
-- L["draiksilvl"] = "draiksilvl"
